name: "Nix Flakes"

on:
  push:
    branches:
      - main
      - develop
      - release/*
      - hotfix/*
      - feature/*
      - ci/*

  pull_request:
    paths:
      - "*/src/**"
      - ".github/**"
      - "src/**"
      - Cargo.lock
      - Cargo.toml
      - flake.lock
      - flake.nix
      - rust-toolchain.toml

jobs:
  build-nix-flake:
    name: Build Nix Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build Nix Flake
        run: nix build

      - name: Test executable
        # NOTE: replace `template-rust` with program name
        run: ./result/bin/template-rust --version
